// Demo data — distilled from MyTerraVera/src/data/demo.ts
window.TV_PRODUCTS = [
  { slug:'extra-virgin-cold-pressed-oil', name:'Extra Virgin Cold-Pressed Oil', price:3200, origin:'Tuscany', producerSlug:'rossi-estate', producerName:'Rossi Estate', description:'A single-estate olive oil from century-old Frantoio trees. Cold-pressed within hours of harvest, this oil has a robust, peppery character with notes of fresh-cut grass and artichoke.', details:['500ml glass bottle','Cold-pressed','Single estate','Harvest 2025'], imageSrc:'../../assets/products/olive-oil.jpg', imageAlt:'Olive oil', badge:{label:'Organic',variant:'producer'}, category:'Oils' },
  { slug:'wildflower-forest-honey', name:'Wildflower Forest Honey', price:1800, origin:'Black Forest', producerSlug:'schwarzwald-imkerei', producerName:'Schwarzwald Imkerei', description:'Unfiltered, raw honey from wildflower meadows at the edge of the Black Forest.', details:['350g glass jar','Raw & unfiltered','Single-origin meadow'], imageSrc:'../../assets/products/honey.jpg', imageAlt:'Honey', category:'Honey' },
  { slug:'sun-dried-tomato-tapenade', name:'Sun-Dried Tomato Tapenade', price:1450, origin:'Andalusia', producerSlug:'casa-del-sol', producerName:'Casa del Sol', description:'Ripe tomatoes from the Murcian huerta, sun-dried for three days and blended with local olive oil, capers, and a whisper of smoked paprika.', details:['200g jar','Sun-dried','No preservatives','Vegan'], imageSrc:'../../assets/products/tapenade.jpg', imageAlt:'Tapenade', badge:{label:'Bestseller',variant:'bestseller'}, category:'Preserves' },
  { slug:'hand-thrown-terracotta-vase', name:'Hand-Thrown Terracotta Vase', price:8500, origin:'Alentejo', producerSlug:'atelier-alentejo', producerName:'Atelier Alentejo', description:'Each vase is individually hand-thrown on a traditional kick wheel and fired in a wood-burning kiln.', details:['Height: 25cm','Hand-thrown','Wood-fired','Each piece unique'], imageSrc:'../../assets/products/vase.jpg', imageAlt:'Vase', category:'Ceramics' },
  { slug:'lavender-savon-de-marseille', name:'Lavender Savon de Marseille', price:1200, origin:'Provence', producerSlug:'maison-lavande', producerName:'Maison Lavande', description:'Cold-process soap made with pure lavender essential oil from Valensole and organic olive oil.', details:['150g bar','Cold-process','6-week cure','Organic ingredients'], imageSrc:'../../assets/products/savon.jpg', imageAlt:'Savon', badge:{label:'Organic',variant:'producer'}, category:'Body Care' },
  { slug:'smoked-paprika-flakes', name:'Smoked Paprika Flakes', price:950, origin:'Andalusia', producerSlug:'casa-del-sol', producerName:'Casa del Sol', description:'Pimientos de la Vera, slowly smoked over holm oak for two weeks.', details:['75g tin','Oak-smoked','Hand-crushed'], imageSrc:'../../assets/products/paprika.jpg', imageAlt:'Paprika', category:'Spices' },
  { slug:'truffle-infused-olive-oil', name:'Truffle-Infused Olive Oil', price:4500, origin:'Tuscany', producerSlug:'rossi-estate', producerName:'Rossi Estate', description:'Extra virgin olive oil infused with fresh black truffle shavings from the Umbrian hills.', details:['250ml bottle','Real truffle shavings','Cold-infused','Limited batch'], imageSrc:'../../assets/products/truffle-oil.jpg', imageAlt:'Truffle oil', badge:{label:'Limited',variant:'limited'}, category:'Oils' },
  { slug:'acacia-honey', name:'Acacia Honey', price:2200, origin:'Black Forest', producerSlug:'schwarzwald-imkerei', producerName:'Schwarzwald Imkerei', description:'Light, delicate, and slow to crystallize.', details:['500g glass jar','Single-varietal','Raw'], imageSrc:'../../assets/products/acacia-honey.jpg', imageAlt:'Acacia honey', category:'Honey' },
];

window.TV_PRODUCERS = [
  { slug:'rossi-estate', name:'Rossi Estate', region:'Tuscany', country:'Italy', specialty:'Olive Oil', tagline:'Four centuries of liquid gold', storyHeadline:'Traditional Know-How from the Rossi Estate', quote:"The secret isn't in the press, it's in the patience.", imageSrc:'../../assets/producers/rossi-estate.jpg', heroImageSrc:'../../assets/regions/italy.jpg', established:'1640', badges:['Organic','Family-Owned'], savoirFaire:[
    { title:'Manual Harvest', description:'Individual hand-picking ensures only the perfectly ripe olives are selected, avoiding the bruising common in mechanical harvesting.' },
    { title:'Cold Extraction', description:'Within six hours of harvest, olives are pressed at temperatures never exceeding 27°C to preserve their delicate polyphenols and intense aroma.' },
    { title:'Restful Decantation', description:'The oil is allowed to settle naturally in steel fusti rather than being forced through filters, maintaining its full-bodied character.' },
  ]},
  { slug:'schwarzwald-imkerei', name:'Schwarzwald Imkerei', region:'Black Forest', country:'Germany', specialty:'Honey', tagline:'Wild honey from ancient forests', imageSrc:'../../assets/producers/schwarzwald-imkerei.jpg', established:'1987', badges:['Raw','Handmade'] },
];

window.TV_STORY = { title:'The liquid gold of the Maremma', subtitle:'A week with Matteo Rossi in his Tuscan olive groves', excerpt:'In the heart of Tuscany, Matteo Rossi continues a tradition that spans four centuries. His artisanal cold-pressing techniques preserve the volatile aromas of the earth.', imageSrc:'../../assets/stories/maremma.jpg', imageAlt:'Tuscan olive grove' };
